### ISSUE TITLE
BE: Add Dice Mechanics

### ISSUE THREAD

**Issue by corsin-lehre** [keykey7/fabbwled#19]
**Is your feature request related to a problem? Please describe.**
We need a mechanic to role the dice

**Describe the solution you'd like**
- The ability to roll the dice when accessing an endpoint. Probably needs to be based on the JSESSIONI

**Comment by keykey7** [comment]
might require additional meta information: 
https://github.com/keykey7/fabbwled/blob/main/fabbwled-backend/src/main/java/ch/bbw/fabbwled/lands/book/SectionNode.java#L163 currently has a`clickId`... might require an additional, optional `dice: 2` attribute...

**Comment by MagischerWolf05** [comment]
For some Dice Roles we could actually add a mecanic to the Yaml ask @Nilstrieb (because he knows how). Because a Large proportion of the Dice Roles are built the same Way.
![grafik](https://github.com/keykey7/fabbwled/assets/70324708/9c8db011-b26e-4fa4-b0b2-eed8f3a3ad7a)
![grafik](https://github.com/keykey7/fabbwled/assets/70324708/a61b8a8e-3e0d-4d32-8b3e-6f13f568778b)

**Comment by Nilstrieb** [comment]
these sections have this "add 2 if" clause, which seems complex and java-only. Do you have more sections that are actually simple? or will all dice sections need to be written in java?
