### ISSUE TITLE
Spring Config UTF8 not supported

### ISSUE THREAD

**Issue by Noeell** [keykey7/fabbwled#467]
**Describe the bug**
Calling the backend from frontend gives back a HTTP 415

**Screenshots**
![grafik](https://github.com/keykey7/fabbwled/assets/85216314/f37b5141-6f8b-4549-a3ad-fa9c71a961e9)
![grafik](https://github.com/keykey7/fabbwled/assets/85216314/4173d418-234d-4f0e-881a-0ab0766a5fb1)

**Expected behavior**
Support UTF-8

PS: Please inform @Noeell when it is solved

**Comment by Nilstrieb** [comment]
wtf

**Comment by Nilstrieb** [comment]
i took a look at it and was unable to find anything. this is very weird. I will bring it up at the meeting today and assign someone.

**Comment by Nilstrieb** [comment]
@Rwael this is a high priority issue. You should drop your current tasks and fix this.
@MagischerWolf05 dies ist ein hoher priorität problem. du solltest fallenlassen deine aktuellen aufgaben und reparieren das.

**Comment by keykey7** [comment]
we need a test for the `POST /api/player` it's the only affected endpoint so far.

**Comment by Nilstrieb** [comment]
I just tested this with another spring boot project of mine, and it worked perfectly fine. Somewhere is very wrong with our backend.

**Comment by Nilstrieb** [comment]
i found the issue, it's something incredibly dumb and spring is literally worse than useless in giving any error messages whatsoever. thanks spring, you great developer friendly framework!
somewhere deep in the **DEBUG** logs for spring we find this (which should absolutely be an _error_ log or crash instead, wtf
```
17:37:39 DEBUG 23036 --- [nio-8080-exec-1] .c.j.MappingJackson2HttpMessageConverter : Failed to evaluate Jackson deserialization for type [[simple type, class ch.bbw.fabbwled.lands.character.Character$CharacterCreateDto2]]

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class ch.bbw.fabbwled.lands.book.SectionId]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.15.2.jar:2.15.2]
```

well, we're trying to deserialize `Character.CharacterCreateDto` from the user. so far so good. But this is where the fun starts. This type cannot be serialized to JSON! That's because it contains a `PlayerSession.PlayerDto`, which in turn contains a `Map<SectionId, Integer>` for the tick boxes. `SectionId` is not a string, so it cannot be turned into a JSON key.

As we see, the bug is trivial, but spring does its best to successfully hide it from us. Implicit magic ftw!

As for fixing it, the simplest solution I see is to convince jackson that our section id is a very good and friendly string and write a serializer/deserializer for it.
